### PR TITLE
Refactor ExistsByHash to allow chaining query builder methods

### PR DESCRIPTION
**Pull request by EriBloo**
Hi,

I recently switched one of our projects to this package. For previous package I had created validation rule which I have adapted to work with yours.

This validation rule is based on Laravel Exists rule and allows chaining constraints on query builder:

```php
validator(
    ['id' => User::idToHash(1)],
    ['id' => new ExistsByHash(User::class)->where('name', 'Admin')],
);
```

I also added support for custom message and attribute so you could do:
```php
validator(
    ['id' => User::idToHash(1)],
    ['id' => new ExistsByHash(User::class)],
    ['id.existsByHash' => 'Incorrect :attribute'],
    ['id' => 'user'],
);
```
to get `Incorrect user` validation message. If no custom rule was specified there is a fallback to Exists rule message.

### CODE REVIEW

**Comment by EriBloo** [comment]
I added one more commit to use qualified columns in `byHash` scope. Current version may cause `Column 'id' in where clause is ambiguous` errors when used with joins.

**Review by veelasky — APPROVED** [review]

**Comment by veelasky** [comment]
Ho @EriBloo thanks for the contributions, I noticed that if we push this, we should drop support for laravel 7-9, due to deprecation in `Illuminate\Contracts\Validation\Rule`

I wouldn't mind to release it under 4.x version, please also update the workflow to only include laravel 10.

**Comment by EriBloo** [comment]
Hi @veelasky. I work with Laravel 10 so I naturally pushed version compatible with it and forgot that current version is used by older Laravel as well. I don't mind refactoring it to the older Rule interface if you'd like, there is no reason to force next major version. Please tell me which approach is better for you ;)

**Comment by veelasky** [comment]
Hello @EriBloo,

Given the current situation, as there hasn't been a significant feature update, I aim to continue supporting lower Laravel versions, unless the deprecated class is removed or until a major feature such as prefix/suffix support is introduced.

**Comment by EriBloo** [comment]
I understand. But I'm not sure which approach you would like to take with this PR. Would you prefere me to refactor it to support Laravel versions 7-9 or release it under 4.x as is?

**Pull request merged**
